apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: pipeline
  name: pipeline
  namespace: default
spec:
  selector:
    matchLabels:
      app: pipeline
  template:
    metadata:
      labels:
        app: pipeline
    spec:
      containers:
      - image: gcr.io/amit-kub-proj/pipeline:ee661b4a1532503448cf2bb534e370b9edf4bdcc
        name: pipeline
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
